In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
#Change filepath '01_Raw_Data/2014_data.csv' when running the code on local machine
year_2014_df = pd.read_csv('01_Raw_Data/2014_data.csv', low_memory=False)
with open("01_Raw_Data/2014_codes.json", "r") as f_open:
    code_maps_2014 = json.load(f_open)



# year_2014_df = pd.read_csv('01_Raw_Data/28_3144_compressed_2014_data.csv/2014_data.csv')
# year_2015_df = pd.read_csv('01_Raw_Data/28_3144_compressed_2015_data.csv/2015_data.csv')

In [3]:
#Change dtypes for '358_cause_recode'
year_2014_df['358_cause_recode'] = year_2014_df['358_cause_recode'].astype(dtype=np.int64)

In [4]:
#year_2014_df

In [5]:
#Check dytpes
# year_2014_df.dtypes

In [6]:
#Drop irrelavent columns 
year_2014_df_2 = year_2014_df.drop(columns=['resident_status', 'education_1989_revision', 'age_recode_52', 'age_recode_12', 'education_reporting_flag', 'age_substitution_flag', 'place_of_death_and_decedents_status', 'current_data_year', 'injury_at_work', 'method_of_disposition', 'autopsy', 'activity_code', 'place_of_injury_for_causes_w00_y34_except_y06_and_y07_', 'icd_code_10th_revision', 'race', 'bridged_race_flag', 'race_imputation_flag', 'race_recode_3', 'race_recode_5', 'hispanic_origin', 'hispanic_originrace_recode', 'detail_age_type', 'manner_of_death', 'number_of_entity_axis_conditions', 'entity_condition_1', 'entity_condition_2', 'entity_condition_3', 'entity_condition_4', 'entity_condition_5', 'entity_condition_6', 'entity_condition_7', 'entity_condition_8', 'entity_condition_9', 'entity_condition_10', 'entity_condition_11', 'entity_condition_12', 'entity_condition_13', 'entity_condition_14', 'entity_condition_15', 'entity_condition_16', 'entity_condition_17', 'entity_condition_18', 'entity_condition_19', 'entity_condition_20', 'number_of_record_axis_conditions', 'record_condition_1', 'record_condition_2', 'record_condition_3', 'record_condition_4', 'record_condition_5', 'record_condition_6', 'record_condition_7', 'record_condition_8', 'record_condition_9', 'record_condition_10', 'record_condition_11', 'record_condition_12', 'record_condition_13', 'record_condition_14', 'record_condition_15', 'record_condition_16', 'record_condition_17', 'record_condition_18', 'record_condition_19', 'record_condition_20'])

In [7]:
# Check Dtypes of new dataframe
# year_2014_df_2.dtypes

In [8]:
#Find NAN for every column
# year_2014_df_2['month_of_death'].unique()

In [9]:
#Drop NAN from 2003 education
year_2014_df_2 = year_2014_df_2.dropna(subset=['education_2003_revision'])
year_2014_df_2

,education_2003_revision,month_of_death,sex,detail_age,age_recode_27,infant_age_recode_22,marital_status,day_of_week_of_death,358_cause_recode,113_cause_recode,130_infant_cause_recode,39_cause_recode
0,2.0,1,M,87,23,NaN,M,4,238,70,NaN,24
1,2.0,1,M,58,17,NaN,D,3,214,62,NaN,21
2,7.0,1,F,75,21,NaN,W,2,267,86,NaN,28
3,6.0,1,M,74,20,NaN,D,1,228,68,NaN,22
4,3.0,1,M,64,18,NaN,D,2,214,62,NaN,21
5,5.0,1,F,93,24,NaN,W,4,280,111,NaN,37
6,4.0,1,M,82,22,NaN,M,6,215,63,NaN,21
7,4.0,1,M,55,17,NaN,S,6,214,62,NaN,21
8,3.0,1,F,86,23,NaN,W,6,175,111,NaN,37
9,3.0,1,M,23,10,NaN,S,4,429,125,NaN,40
10,3.0,1,F,79,21,NaN,W,2,225,68,NaN,22
11,2.0,1,M,86,23,NaN,W,3,188,51,NaN,37
12,4.0,1,F,85,23,NaN,W,3,225,68,NaN,22
13,3.0,1,F,84,22,NaN,W,4,93,27,NaN,8
14,3.0,1,F,66,19,NaN,D,6,93,27,NaN,8
15,4.0,1,F,70,20,NaN,M,4,215,63,NaN,21
16,6.0,1,F,92,24,NaN,W,2,228,68,NaN,22
17,5.0,1,F,82,22,NaN,W,5,215,63,NaN,21
18,1.0,1,M,83,22,NaN,M,4,267,86,NaN,28
19,3.0,1,F,84,22,NaN,W,1,129,39,NaN,13
20,3.0,1,M,80,22,NaN,M,4,215,63,NaN,21
21,8.0,1,M,66,19,NaN,M,7,113,33,NaN,11
22,3.0,1,F,73,20,NaN,W,5,211,59,NaN,21
23,7.0,1,F,51,16,NaN,M,4,104,29,NaN,9
24,4.0,1,M,20,10,NaN,S,6,429,125,NaN,40
25,7.0,1,M,45,15,NaN,M,1,429,125,NaN,40
26,7.0,1,M,71,20,NaN,M,4,211,59,NaN,21
27,3.0,1,F,46,15,NaN,D,6,298,94,NaN,30
28,2.0,1,M,78,21,NaN,M,1,81,23,NaN,6
29,2.0,1,M,72,20,NaN,W,4,379,110,NaN,36
...,...,...,...,...,...,...,...,...,...,...,...,...
2631141,1.0,12,M,69,19,NaN,U,3,436,129,NaN,41
2631142,9.0,12,M,61,18,NaN,U,2,77,21,NaN,15
2631143,9.0,11,M,66,19,NaN,W,1,211,59,NaN,21
2631144,9.0,12,M,58,17,NaN,U,4,214,62,NaN,21
2631145,9.0,7,M,45,15,NaN,U,1,379,110,NaN,36
2631146,6.0,12,M,73,20,NaN,S,1,93,27,NaN,8
2631147,1.0,12,F,21,1,2.0,S,6,363,108,106.0,33
2631148,1.0,12,M,6,1,2.0,S,2,358,108,89.0,33
2631149,9.0,12,F,68,19,NaN,S,4,93,27,NaN,8
2631150,9.0,12,M,66,19,NaN,U,2,214,62,NaN,21
2631151,1.0,11,M,55,17,NaN,M,6,122,36,NaN,15
2631152,1.0,11,M,85,23,NaN,D,2,159,46,NaN,16
2631153,9.0,12,M,57,17,NaN,U,6,379,110,NaN,36
2631154,9.0,12,M,73,20,NaN,U,7,215,63,NaN,21
2631155,1.0,12,M,3,1,5.0,S,5,364,108,117.0,33
2631156,1.0,9,F,3,1,2.0,S,2,358,108,89.0,33
2631157,9.0,12,M,61,18,NaN,S,7,215,63,NaN,21
2631158,9.0,11,F,90,24,NaN,U,7,215,63,NaN,21
2631159,4.0,11,M,85,23,NaN,S,1,215,63,NaN,21
2631160,1.0,12,M,2,1,2.0,S,7,358,108,89.0,33
2631161,9.0,12,M,90,24,NaN,U,1,215,63,NaN,21
2631162,9.0,12,F,85,23,NaN,U,6,175,111,NaN,37
2631163,1.0,11,M,79,21,NaN,S,1,215,63,NaN,21
2631164,9.0,12,M,67,19,NaN,U,3,159,46,NaN,16
2631165,9.0,12,M,54,16,NaN,U,5,257,78,NaN,27
2631166,6.0,12,M,84,22,NaN,S,2,207,56,NaN,20
2631167,9.0,12,F,74,20,NaN,S,7,215,63,NaN,21
2631168,1.0,12,M,7,1,1.0,S,4,358,108,89.0,33
2631169,9.0,2,M,49,15,NaN,U,1,214,62,NaN,21
2631170,1.0,5,M,39,1,1.0,S,2,364,108,117.0,33

In [10]:
# Create new column for seasons 
# Bin into seasons 
size_bins = [0, 3, 6, 9, 12]
group_names = ["Winter", "Spring", "Summer", "Fall"]

# add season bins columns & row Labels
year_2014_df_2["Seasons"] = pd.cut(year_2014_df_2["month_of_death"], size_bins, labels=group_names)
year_2014_df_2["Seasons"] 
year_2014_df_2

,education_2003_revision,month_of_death,sex,detail_age,age_recode_27,infant_age_recode_22,marital_status,day_of_week_of_death,358_cause_recode,113_cause_recode,130_infant_cause_recode,39_cause_recode,Seasons
0,2.0,1,M,87,23,NaN,M,4,238,70,NaN,24,Winter
1,2.0,1,M,58,17,NaN,D,3,214,62,NaN,21,Winter
2,7.0,1,F,75,21,NaN,W,2,267,86,NaN,28,Winter
3,6.0,1,M,74,20,NaN,D,1,228,68,NaN,22,Winter
4,3.0,1,M,64,18,NaN,D,2,214,62,NaN,21,Winter
5,5.0,1,F,93,24,NaN,W,4,280,111,NaN,37,Winter
6,4.0,1,M,82,22,NaN,M,6,215,63,NaN,21,Winter
7,4.0,1,M,55,17,NaN,S,6,214,62,NaN,21,Winter
8,3.0,1,F,86,23,NaN,W,6,175,111,NaN,37,Winter
9,3.0,1,M,23,10,NaN,S,4,429,125,NaN,40,Winter
10,3.0,1,F,79,21,NaN,W,2,225,68,NaN,22,Winter
11,2.0,1,M,86,23,NaN,W,3,188,51,NaN,37,Winter
12,4.0,1,F,85,23,NaN,W,3,225,68,NaN,22,Winter
13,3.0,1,F,84,22,NaN,W,4,93,27,NaN,8,Winter
14,3.0,1,F,66,19,NaN,D,6,93,27,NaN,8,Winter
15,4.0,1,F,70,20,NaN,M,4,215,63,NaN,21,Winter
16,6.0,1,F,92,24,NaN,W,2,228,68,NaN,22,Winter
17,5.0,1,F,82,22,NaN,W,5,215,63,NaN,21,Winter
18,1.0,1,M,83,22,NaN,M,4,267,86,NaN,28,Winter
19,3.0,1,F,84,22,NaN,W,1,129,39,NaN,13,Winter
20,3.0,1,M,80,22,NaN,M,4,215,63,NaN,21,Winter
21,8.0,1,M,66,19,NaN,M,7,113,33,NaN,11,Winter
22,3.0,1,F,73,20,NaN,W,5,211,59,NaN,21,Winter
23,7.0,1,F,51,16,NaN,M,4,104,29,NaN,9,Winter
24,4.0,1,M,20,10,NaN,S,6,429,125,NaN,40,Winter
25,7.0,1,M,45,15,NaN,M,1,429,125,NaN,40,Winter
26,7.0,1,M,71,20,NaN,M,4,211,59,NaN,21,Winter
27,3.0,1,F,46,15,NaN,D,6,298,94,NaN,30,Winter
28,2.0,1,M,78,21,NaN,M,1,81,23,NaN,6,Winter
29,2.0,1,M,72,20,NaN,W,4,379,110,NaN,36,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2631141,1.0,12,M,69,19,NaN,U,3,436,129,NaN,41,Fall
2631142,9.0,12,M,61,18,NaN,U,2,77,21,NaN,15,Fall
2631143,9.0,11,M,66,19,NaN,W,1,211,59,NaN,21,Fall
2631144,9.0,12,M,58,17,NaN,U,4,214,62,NaN,21,Fall
2631145,9.0,7,M,45,15,NaN,U,1,379,110,NaN,36,Summer
2631146,6.0,12,M,73,20,NaN,S,1,93,27,NaN,8,Fall
2631147,1.0,12,F,21,1,2.0,S,6,363,108,106.0,33,Fall
2631148,1.0,12,M,6,1,2.0,S,2,358,108,89.0,33,Fall
2631149,9.0,12,F,68,19,NaN,S,4,93,27,NaN,8,Fall
2631150,9.0,12,M,66,19,NaN,U,2,214,62,NaN,21,Fall
2631151,1.0,11,M,55,17,NaN,M,6,122,36,NaN,15,Fall
2631152,1.0,11,M,85,23,NaN,D,2,159,46,NaN,16,Fall
2631153,9.0,12,M,57,17,NaN,U,6,379,110,NaN,36,Fall
2631154,9.0,12,M,73,20,NaN,U,7,215,63,NaN,21,Fall
2631155,1.0,12,M,3,1,5.0,S,5,364,108,117.0,33,Fall
2631156,1.0,9,F,3,1,2.0,S,2,358,108,89.0,33,Summer
2631157,9.0,12,M,61,18,NaN,S,7,215,63,NaN,21,Fall
2631158,9.0,11,F,90,24,NaN,U,7,215,63,NaN,21,Fall
2631159,4.0,11,M,85,23,NaN,S,1,215,63,NaN,21,Fall
2631160,1.0,12,M,2,1,2.0,S,7,358,108,89.0,33,Fall
2631161,9.0,12,M,90,24,NaN,U,1,215,63,NaN,21,Fall
2631162,9.0,12,F,85,23,NaN,U,6,175,111,NaN,37,Fall
2631163,1.0,11,M,79,21,NaN,S,1,215,63,NaN,21,Fall
2631164,9.0,12,M,67,19,NaN,U,3,159,46,NaN,16,Fall
2631165,9.0,12,M,54,16,NaN,U,5,257,78,NaN,27,Fall
2631166,6.0,12,M,84,22,NaN,S,2,207,56,NaN,20,Fall
2631167,9.0,12,F,74,20,NaN,S,7,215,63,NaN,21,Fall
2631168,1.0,12,M,7,1,1.0,S,4,358,108,89.0,33,Fall
2631169,9.0,2,M,49,15,NaN,U,1,214,62,NaN,21,Winter
2631170,1.0,5,M,39,1,1.0,S,2,364,108,117.0,33,Spring

In [33]:
#Export as csv
year_2014_df_2.to_csv(r'03_Cleaned_Data\masterfile.csv', index = False)

In [12]:
#CARDIOVASCULAR DISEASE CODES 
#KEEP(214, 027, 053, 062, 18)

In [13]:
#Make a copy of this dataset to do analysis for specific diseases 
year_2014_df_3 = year_2014_df_2

In [14]:
# year_2014_df_3

In [15]:
#use iloc for those disease codes 
df214 = year_2014_df_3[year_2014_df_3.iloc[:, 8] == 214]
df27 = year_2014_df_3[year_2014_df_3.iloc[:, 8] == 27]
df53 = year_2014_df_3[year_2014_df_3.iloc[:, 8] == 53]
df62 = year_2014_df_3[year_2014_df_3.iloc[:, 8] == 62]
df18 = year_2014_df_3[year_2014_df_3.iloc[:, 8] == 18]
# print(df)

In [32]:
df1 = df214.copy()
df2 = df27.copy()
df3 = df53.copy()
df4 = df62.copy()
df5 = df18.copy()

cardio_df = pd.concat([df1, df2, df3, df4, df5])
cardio_df

#Export as csv
cardio_df.to_csv(r'03_Cleaned_Data\Cardiomortality.csv', index = True)

In [17]:
#CHILD DISEASE CODES
#Highest mortality of kids under 1 years old vs 1 year/2 year/3 year/ 4 year
child_disease_df = year_2014_df_2

In [18]:
child_disease_df = child_disease_df.dropna(subset=['age_recode_27'])
child_disease_df = child_disease_df.drop(columns=['day_of_week_of_death', 'education_2003_revision', 'infant_age_recode_22', 'marital_status', '358_cause_recode', '113_cause_recode', '39_cause_recode'])
child_disease_df

,month_of_death,sex,detail_age,age_recode_27,130_infant_cause_recode,Seasons
0,1,M,87,23,NaN,Winter
1,1,M,58,17,NaN,Winter
2,1,F,75,21,NaN,Winter
3,1,M,74,20,NaN,Winter
4,1,M,64,18,NaN,Winter
5,1,F,93,24,NaN,Winter
6,1,M,82,22,NaN,Winter
7,1,M,55,17,NaN,Winter
8,1,F,86,23,NaN,Winter
9,1,M,23,10,NaN,Winter
10,1,F,79,21,NaN,Winter
11,1,M,86,23,NaN,Winter
12,1,F,85,23,NaN,Winter
13,1,F,84,22,NaN,Winter
14,1,F,66,19,NaN,Winter
15,1,F,70,20,NaN,Winter
16,1,F,92,24,NaN,Winter
17,1,F,82,22,NaN,Winter
18,1,M,83,22,NaN,Winter
19,1,F,84,22,NaN,Winter
20,1,M,80,22,NaN,Winter
21,1,M,66,19,NaN,Winter
22,1,F,73,20,NaN,Winter
23,1,F,51,16,NaN,Winter
24,1,M,20,10,NaN,Winter
25,1,M,45,15,NaN,Winter
26,1,M,71,20,NaN,Winter
27,1,F,46,15,NaN,Winter
28,1,M,78,21,NaN,Winter
29,1,M,72,20,NaN,Winter
...,...,...,...,...,...,...
2631141,12,M,69,19,NaN,Fall
2631142,12,M,61,18,NaN,Fall
2631143,11,M,66,19,NaN,Fall
2631144,12,M,58,17,NaN,Fall
2631145,7,M,45,15,NaN,Summer
2631146,12,M,73,20,NaN,Fall
2631147,12,F,21,1,106.0,Fall
2631148,12,M,6,1,89.0,Fall
2631149,12,F,68,19,NaN,Fall
2631150,12,M,66,19,NaN,Fall
2631151,11,M,55,17,NaN,Fall
2631152,11,M,85,23,NaN,Fall
2631153,12,M,57,17,NaN,Fall
2631154,12,M,73,20,NaN,Fall
2631155,12,M,3,1,117.0,Fall
2631156,9,F,3,1,89.0,Summer
2631157,12,M,61,18,NaN,Fall
2631158,11,F,90,24,NaN,Fall
2631159,11,M,85,23,NaN,Fall
2631160,12,M,2,1,89.0,Fall
2631161,12,M,90,24,NaN,Fall
2631162,12,F,85,23,NaN,Fall
2631163,11,M,79,21,NaN,Fall
2631164,12,M,67,19,NaN,Fall
2631165,12,M,54,16,NaN,Fall
2631166,12,M,84,22,NaN,Fall
2631167,12,F,74,20,NaN,Fall
2631168,12,M,7,1,89.0,Fall
2631169,2,M,49,15,NaN,Winter
2631170,5,M,39,1,117.0,Spring

In [19]:
# Bin into age
size_bins = [0, 2, 3, 4, 5, 6, 27]
group_names = ["Under 1 Years Old", "1 Years Old", "2 Years Old", "3 Years Old", "4 Years Old", "NaN"]

# add season bins columns & row Labels
child_disease_df["InfantAge"] = pd.cut(child_disease_df["age_recode_27"], size_bins, labels=group_names)
child_disease_df["InfantAge"]
child_disease_df

,month_of_death,sex,detail_age,age_recode_27,130_infant_cause_recode,Seasons,InfantAge
0,1,M,87,23,NaN,Winter,NaN
1,1,M,58,17,NaN,Winter,NaN
2,1,F,75,21,NaN,Winter,NaN
3,1,M,74,20,NaN,Winter,NaN
4,1,M,64,18,NaN,Winter,NaN
5,1,F,93,24,NaN,Winter,NaN
6,1,M,82,22,NaN,Winter,NaN
7,1,M,55,17,NaN,Winter,NaN
8,1,F,86,23,NaN,Winter,NaN
9,1,M,23,10,NaN,Winter,NaN
10,1,F,79,21,NaN,Winter,NaN
11,1,M,86,23,NaN,Winter,NaN
12,1,F,85,23,NaN,Winter,NaN
13,1,F,84,22,NaN,Winter,NaN
14,1,F,66,19,NaN,Winter,NaN
15,1,F,70,20,NaN,Winter,NaN
16,1,F,92,24,NaN,Winter,NaN
17,1,F,82,22,NaN,Winter,NaN
18,1,M,83,22,NaN,Winter,NaN
19,1,F,84,22,NaN,Winter,NaN
20,1,M,80,22,NaN,Winter,NaN
21,1,M,66,19,NaN,Winter,NaN
22,1,F,73,20,NaN,Winter,NaN
23,1,F,51,16,NaN,Winter,NaN
24,1,M,20,10,NaN,Winter,NaN
25,1,M,45,15,NaN,Winter,NaN
26,1,M,71,20,NaN,Winter,NaN
27,1,F,46,15,NaN,Winter,NaN
28,1,M,78,21,NaN,Winter,NaN
29,1,M,72,20,NaN,Winter,NaN
...,...,...,...,...,...,...,...
2631141,12,M,69,19,NaN,Fall,NaN
2631142,12,M,61,18,NaN,Fall,NaN
2631143,11,M,66,19,NaN,Fall,NaN
2631144,12,M,58,17,NaN,Fall,NaN
2631145,7,M,45,15,NaN,Summer,NaN
2631146,12,M,73,20,NaN,Fall,NaN
2631147,12,F,21,1,106.0,Fall,Under 1 Years Old
2631148,12,M,6,1,89.0,Fall,Under 1 Years Old
2631149,12,F,68,19,NaN,Fall,NaN
2631150,12,M,66,19,NaN,Fall,NaN
2631151,11,M,55,17,NaN,Fall,NaN
2631152,11,M,85,23,NaN,Fall,NaN
2631153,12,M,57,17,NaN,Fall,NaN
2631154,12,M,73,20,NaN,Fall,NaN
2631155,12,M,3,1,117.0,Fall,Under 1 Years Old
2631156,9,F,3,1,89.0,Summer,Under 1 Years Old
2631157,12,M,61,18,NaN,Fall,NaN
2631158,11,F,90,24,NaN,Fall,NaN
2631159,11,M,85,23,NaN,Fall,NaN
2631160,12,M,2,1,89.0,Fall,Under 1 Years Old
2631161,12,M,90,24,NaN,Fall,NaN
2631162,12,F,85,23,NaN,Fall,NaN
2631163,11,M,79,21,NaN,Fall,NaN
2631164,12,M,67,19,NaN,Fall,NaN
2631165,12,M,54,16,NaN,Fall,NaN
2631166,12,M,84,22,NaN,Fall,NaN
2631167,12,F,74,20,NaN,Fall,NaN
2631168,12,M,7,1,89.0,Fall,Under 1 Years Old
2631169,2,M,49,15,NaN,Winter,NaN
2631170,5,M,39,1,117.0,Spring,Under 1 Years Old

In [20]:
child_disease_df = child_disease_df.drop(child_disease_df[child_disease_df.InfantAge == "NaN"].index)

In [21]:
child_disease_df = child_disease_df.drop(columns=['detail_age', 'age_recode_27'])
child_disease_df

#Export to CSV
child_disease_df.to_csv(r'03_Cleaned_Data\childmortality.csv', index = True)

In [22]:
child_disease_df

,month_of_death,sex,130_infant_cause_recode,Seasons,InfantAge
190,1,M,110.0,Winter,Under 1 Years Old
214,1,F,98.0,Winter,Under 1 Years Old
215,1,M,115.0,Winter,Under 1 Years Old
216,1,M,108.0,Winter,Under 1 Years Old
244,1,F,136.0,Winter,Under 1 Years Old
295,1,F,136.0,Winter,Under 1 Years Old
604,1,M,135.0,Winter,Under 1 Years Old
627,2,M,135.0,Winter,Under 1 Years Old
666,2,F,108.0,Winter,Under 1 Years Old
667,2,F,136.0,Winter,Under 1 Years Old
716,3,M,84.0,Winter,Under 1 Years Old
719,3,M,NaN,Winter,4 Years Old
777,3,M,76.0,Winter,Under 1 Years Old
799,3,F,NaN,Winter,1 Years Old
819,3,M,NaN,Winter,4 Years Old
914,3,F,135.0,Winter,Under 1 Years Old
946,3,M,NaN,Winter,1 Years Old
947,3,F,106.0,Winter,Under 1 Years Old
972,4,F,135.0,Spring,Under 1 Years Old
1051,4,F,135.0,Spring,Under 1 Years Old
1105,4,M,NaN,Spring,1 Years Old
1134,3,M,9.0,Winter,Under 1 Years Old
1146,4,M,NaN,Spring,3 Years Old
1156,5,F,NaN,Spring,4 Years Old
1201,4,F,106.0,Spring,Under 1 Years Old
1235,4,M,80.0,Spring,Under 1 Years Old
1252,4,F,117.0,Spring,Under 1 Years Old
1443,5,M,130.0,Spring,Under 1 Years Old
1465,5,F,106.0,Spring,Under 1 Years Old
1574,6,F,66.0,Spring,Under 1 Years Old
...,...,...,...,...,...
2629382,12,M,NaN,Fall,4 Years Old
2629427,12,M,61.0,Fall,Under 1 Years Old
2629592,12,F,136.0,Fall,Under 1 Years Old
2629620,12,F,65.0,Fall,Under 1 Years Old
2629623,12,M,106.0,Fall,Under 1 Years Old
2629648,12,M,136.0,Fall,Under 1 Years Old
2629721,12,M,117.0,Fall,Under 1 Years Old
2629782,11,F,NaN,Fall,1 Years Old
2629834,12,M,155.0,Fall,Under 1 Years Old
2629900,12,M,62.0,Fall,Under 1 Years Old
2629914,12,F,128.0,Fall,Under 1 Years Old
2630152,12,M,89.0,Fall,Under 1 Years Old
2630216,12,M,117.0,Fall,Under 1 Years Old
2630388,12,M,NaN,Fall,3 Years Old
2630490,12,M,NaN,Fall,2 Years Old
2630492,12,F,96.0,Fall,Under 1 Years Old
2630612,12,M,136.0,Fall,Under 1 Years Old
2630753,12,F,136.0,Fall,Under 1 Years Old
2630841,12,M,NaN,Fall,1 Years Old
2630873,12,F,82.0,Fall,Under 1 Years Old
2630951,12,M,117.0,Fall,Under 1 Years Old
2631003,10,F,136.0,Fall,Under 1 Years Old
2631019,12,M,89.0,Fall,Under 1 Years Old
2631147,12,F,106.0,Fall,Under 1 Years Old
2631148,12,M,89.0,Fall,Under 1 Years Old
2631155,12,M,117.0,Fall,Under 1 Years Old
2631156,9,F,89.0,Summer,Under 1 Years Old
2631160,12,M,89.0,Fall,Under 1 Years Old
2631168,12,M,89.0,Fall,Under 1 Years Old
2631170,5,M,117.0,Spring,Under 1 Years Old

In [23]:
#Seasonal Impact on Mortality 
#Respitory = KEEP(247, 248, 251, 252, 258, 260, 261, 262, 276, 278, 361, 362, 371, 13, 90, 95)
#Circulatory = KEEP(197, 244, 246, 370)

In [24]:
#copy cleaned up dataframe to run specific analysis
seasons_df = year_2014_df_2

In [25]:
#Drop irrelavent columns
seasons_df = seasons_df.drop(columns=['education_2003_revision', 'month_of_death', 'sex', 'detail_age', 'age_recode_27', 'infant_age_recode_22', 'marital_status', 'day_of_week_of_death', '39_cause_recode'])
seasons_df

         358_cause_recode  113_cause_recode  130_infant_cause_recode Seasons
0                     238                70                      NaN  Winter
1                     214                62                      NaN  Winter
2                     267                86                      NaN  Winter
3                     228                68                      NaN  Winter
4                     214                62                      NaN  Winter
5                     280               111                      NaN  Winter
6                     215                63                      NaN  Winter
7                     214                62                      NaN  Winter
8                     175               111                      NaN  Winter
9                     429               125                      NaN  Winter
10                    225                68                      NaN  Winter
11                    188                51                      NaN  Winter
12                    225                68                      NaN  Winter
13                     93                27                      NaN  Winter
14                     93                27                      NaN  Winter
15                    215                63                      NaN  Winter
16                    228                68                      NaN  Winter
17                    215                63                      NaN  Winter
18                    267                86                      NaN  Winter
19                    129                39                      NaN  Winter
20                    215                63                      NaN  Winter
21                    113                33                      NaN  Winter
22                    211                59                      NaN  Winter
23                    104                29                      NaN  Winter
24                    429               125                      NaN  Winter
25                    429               125                      NaN  Winter
26                    211                59                      NaN  Winter
27                    298                94                      NaN  Winter
28                     81                23                      NaN  Winter
29                    379               110                      NaN  Winter
...                   ...               ...                      ...     ...
2631141               436               129                      NaN    Fall
2631142                77                21                      NaN    Fall
2631143               211                59                      NaN    Fall
2631144               214                62                      NaN    Fall
2631145               379               110                      NaN  Summer
2631146                93                27                      NaN    Fall
2631147               363               108                    106.0    Fall
2631148               358               108                     89.0    Fall
2631149                93                27                      NaN    Fall
2631150               214                62                      NaN    Fall
2631151               122                36                      NaN    Fall
2631152               159                46                      NaN    Fall
2631153               379               110                      NaN    Fall
2631154               215                63                      NaN    Fall
2631155               364               108                    117.0    Fall
2631156               358               108                     89.0  Summer
2631157               215                63                      NaN    Fall
2631158               215                63                      NaN    Fall
2631159               215                63                      NaN    Fall
2631160               358               108                     89.0    Fall
2631161               215                63                      NaN    Fall
2631162               175               111                      NaN    Fall
2631163               215                63                      NaN    Fall
2631164               159                46                      NaN    Fall
2631165               257                78                      NaN    Fall
2631166               207                56                      NaN    Fall
2631167               215                63                      NaN    Fall
2631168               358               108                     89.0    Fall
2631169               214                62                      NaN  Winter
2631170               364               108                    117.0  Spring

[2389564 rows x 4 columns]

In [26]:
#Respitory = KEEP(247, 248, 251, 252, 258, 260, 261, 262, 276, 278, 361, 362, 371, 13, 90, 95)
#use iloc for respitory disease codes 
df251 = seasons_df[seasons_df.iloc[:, 0] == 251]
df260 = seasons_df[seasons_df.iloc[:, 0] == 260]
df261 = seasons_df[seasons_df.iloc[:, 0] == 261]
df276 = seasons_df[seasons_df.iloc[:, 0] == 276]
df278 = seasons_df[seasons_df.iloc[:, 0] == 278]
df361 = seasons_df[seasons_df.iloc[:, 0] == 361]
df362 = seasons_df[seasons_df.iloc[:, 0] == 362]
df371 = seasons_df[seasons_df.iloc[:, 0] == 371]
df13 = seasons_df[seasons_df.iloc[:, 0] == 13]
df95 = seasons_df[seasons_df.iloc[:, 0] == 95]

#Dropped several disease codes because no records
#Concact into one datafram for respitory diseases
respiratory_df = pd.concat([df251, df260, df261, df276, df278, df361, df362, df371, df13, df95])
respiratory_df

#Export to CSV
respiratory_df.to_csv(r'03_Cleaned_Data\respiratorymortality.csv', index = True)

In [27]:
#Circulatory = KEEP(197, 244, 246, 370)
#use iloc for circulatory disease codes 
df246 = seasons_df[seasons_df.iloc[:, 0] == 246]
df370 = seasons_df[seasons_df.iloc[:, 0] == 370]

#Dropped 197 & 244 because there were no records 
#Concact into one datafram for respitory diseases
circulatory_df = pd.concat([df246, df370])
circulatory_df

#Export to CSV
circulatory_df.to_csv(r'03_Cleaned_Data\circulatorymortality.csv', index = True)

In [28]:
#College Education on Mortality.

In [29]:
college_df = year_2014_df_2

In [30]:
college_df = college_df.drop(columns=['130_infant_cause_recode', 'month_of_death', 'sex', 'detail_age',  'infant_age_recode_22', 'marital_status', 'day_of_week_of_death', '39_cause_recode', 'Seasons'])

In [31]:
college_df

#Export to CSV
college_df.to_csv(r'03_Cleaned_Data\collegemortality.csv', index = True)